---
title: "legacy_admissions_data_cleaning"
author: "Brecken Enright"
date: "2024-10-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r, show_col_types = FALSE}
legacy_data <- read_csv("2019_2024_legacy_admissions.csv")
cmc_admissions <- read_csv("2019_2024_CMC_admissions.csv")
head(legacy_data)
```

```{r}
cmc_legacy_data <- legacy_data %>%
  filter(school == "CMC")
glimpse(cmc_legacy_data)
```

```{r}
cmc_legacy_data <- cmc_legacy_data %>%
  rename("legacy_admitted" = "num_students_admitted",
         "legacy_enrolled" = "num_students_enrolled")
glimpse(cmc_legacy_data)
```

```{r}
total_admitted = cmc_admissions$admitted
total_enrolled = cmc_admissions$enrolled

cmc_legacy_data <- cbind(cmc_legacy_data, total_admitted, total_enrolled)
glimpse(cmc_legacy_data)
```


```{r}
cmc_legacy_data <- cmc_legacy_data %>%
  select(-num_students_acc_admission) %>%
  mutate(legacy_admitted = as.integer(legacy_admitted),
         legacy_enrolled = as.integer(legacy_enrolled),
         total_admitted = as.integer(total_admitted),
         total_enrolled = as.integer(total_enrolled),
         percent_legacy_admitted = (100*(legacy_admitted/total_admitted)),
         percent_legacy_enrolled = (100*(legacy_enrolled/total_enrolled)))

glimpse(cmc_legacy_data)

```

Subtract legacy from total admitted and enrolled
```{r}
cmc_legacy_data <- cmc_legacy_data %>%
  mutate(not_legacy_enrolled = (total_enrolled - legacy_enrolled),
         not_legacy_admitted = (total_admitted - legacy_admitted))
#write_csv(cmc_legacy_data,"2019-24_cmc_legacy_data.csv")
```

```{r}
legacy_data_2024 <- legacy_data %>%
  filter(year == "2023-2024")
glimpse(legacy_data_2024)
```
```{r}
cmc_admissions_2024 <- cmc_admissions %>%
  filter(year == "2023-2024")
cmc_admissions_2024
hmc_admissions_2024 <- read_csv("HMC_admissions.csv")
hmc_admissions_2024

admissions_2024 <- rbind(cmc_admissions_2024, hmc_admissions_2024)
admissions_2024 
legacy_admitted <- legacy_data_2024$num_students_admitted
legacy_enrolled <- legacy_data_2024$num_students_enrolled
admissions_2024 <- cbind(admissions_2024, legacy_admitted, legacy_enrolled)
admissions_2024

admissions_2024 <- admissions_2024%>%
  mutate(legacy_admitted = as.integer(legacy_admitted),
         legacy_enrolled = as.integer(legacy_enrolled),
         not_legacy_enrolled = (enrolled - legacy_enrolled),
         not_legacy_admitted = (admitted - legacy_admitted))

admissions_2024
write_csv(admissions_2024, "legacy_admissions_2024.csv")

```

